title: "Tamzid Morshed Rubab"
description: "Personal website of Tamzid Morshed Rubab, a researcher in theoretical computer science focusing on algorithms, graph theory, and logic."
theme: minima
favicon: /assets/profile.jpg

plugins:
  - jekyll-sitemap
